language: python
python:
  - "3.6"
  - "3.9"
install:
  make deps
script:
  - make test
  - make lint
  - make docker_build
  - make docker_push
deploy:
provider: heroku
app: afternoon-garden-72119
api_key: ${HEROKU_API_KEY}
